Metrics/LineLength:
  Max: 120

# AbcSize/CyclomaticComplexity is better for what we are concerned about. None of our methods will end up with a large
# amount of statements; just enormous initializations for things like Hashes.
Metrics/MethodLength:
  Enabled: false

Style/FileName:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 8

Style/AccessorMethodName:
  Enabled: false

Style/SignalException:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
